trigger: none

pool: demo_agent_pool



stages:
  - stage: dotnetBuild
    jobs: 
      - job: 
        displayName: dot net restore
        steps:
        - task: Bash@3
          inputs:
            targetType: 'inline'
            script: |
              sudo apt install -y dotnet-sdk-8.0
              dotnet --version
        - task: DotNetCoreCLI@2
          inputs:
            azureSubscription: 'demo_account'
            command: 'restore'
            feedsToUse: 'sejlect'
        - task: DotNetCoreCLI@2
          inputs:
            azureSubscription: 'demo_account'
            command: 'build'
        - task: DotNetCoreCLI@2
          inputs:
            azureSubscription: 'demo_account'
            command: 'publish'
            publishWebProjects: true
            arguments: '-c Release'

# stages:
# - stage: Build
#   jobs:
#   - job: build_publish
#     steps:
#     - task: UseDotNet@2
#       inputs:
#         version: '$(dotnetVersion)'
#         packageType: 'sdk'

#     - script: dotnet restore
#       displayName: 'dotnet restore'

#     - script: dotnet build --configuration $(buildConfig) --no-restore
#       displayName: 'dotnet build'

#     - script: dotnet test  --configuration $(buildConfig) --no-build --logger trx
#       displayName: 'dotnet test'
#       continueOnError: true

#     - task: PublishTestResults@2
#       condition: succeededOrFailed()
#       inputs: { testResultsFormat: 'VSTest', testResultsFiles: '**/*.trx' }

#     - script: dotnet publish --configuration $(buildConfig) --output $(Build.ArtifactStagingDirectory)/publish
#       displayName: 'dotnet publish'

#     - publish: $(Build.ArtifactStagingDirectory)/publish
#       artifact: dotnet-publish

# - stage: Containerize
#   dependsOn: Build
#   jobs:
#   - job: docker
#     steps:
#     - task: Docker@2
#       inputs:
#         containerRegistry: '$(acrName)'
#         repository: '$(imageName)'
#         command: 'buildAndPush'
#         Dockerfile: 'Dockerfile'
#         tags: |
#           $(Build.BuildNumber)
#           latest

# - stage: Deploy_AppService
#   dependsOn: Containerize
#   jobs:
#   - deployment: webapp
#     environment: 'dotnet-prod'
#     strategy:
#       runOnce:
#         deploy:
#           steps:
#           - task: AzureWebAppContainer@1
#             inputs:
#               azureSubscription: 'azure-prod'
#               appName: 'hello-aniket-dotnet'
#               imageName: '$(acrName).azurecr.io/$(imageName):$(Build.BuildNumber)'
